server:
  port: 8888

spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/databaseChangeLog.xml
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/fakegroup
    type: com.zaxxer.hikari.HikariDataSource
